### ISSUE TITLE
Erro em gráfico somente com gerarEntradas

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#132]
Se todas os tipos de gráficos forem executados, somente com gerarEntradas, ocorre o erro:

Traceback (most recent call last):
  File "/home/daniel/Documentos/GI-UFBA/GIT/MT_PEU/Exemplo.py", line 36, in <module>
    Estime.graficos(etapas)
  File "/home/daniel/Documentos/GI-UFBA/GIT/MT_PEU/MT_PEU.py", line 2031, in graficos
    if self.parametros.matriz_covariancia is not None:
AttributeError: Grandeza instance has no attribute 'matriz_covariancia'

**Comment by ddss** [comment]
Incluir teste de controleFLuxo na linha 2154

self.__controleFluxo.incertezaParametros

**Comment by regianesousa** [comment]
Resolvido no commit: a318805d1d46323b8f076cd71e8d2dcd649afe9c
