### ISSUE TITLE
Problemas na rotina de otimização

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#88]
Algumas vez o seguinte ocorre:

ITERACAO: 407
Traceback (most recent call last):
  File "C:/xampp/htdocs/temp/peu-web/motor_de_calculo/peu_wrapper.py", line 464, in <module>
    etapa1.otimiza(limite_inferior=par_lim_inf_est,limite_superior=par_lim_sup_est,algoritmo=Algoritmo,itmax=500,Num_particulas=30,args=func,printit=True)
  File "C:\xampp\htdocs\temp\peu-web\motor_de_calculo\MT_PEU\MT_PEU.py", line 875, in otimiza
    self.__hist_Posicoes.append(self.Otimizacao.historico_posicoes[it][ID_particula])
IndexError: list index out of range

Ainda não esta claro o que gera esse erro, mas aparece de forma intermitente

**Comment by ffmatos** [comment]
Novamente...

ITERACAO: 300
Traceback (most recent call last):
  File "C:/xampp/htdocs/temp/peu-web/motor_de_calculo/peu_wrapper.py", line 474, in <module>
    Num_particulas=30, args=func, printit=True)
  File "C:\xampp\htdocs\temp\peu-web\motor_de_calculo\MT_PEU\MT_PEU.py", line 875, in otimiza
    self.__hist_Posicoes.append(self.Otimizacao.historico_posicoes[it][ID_particula])
IndexError: list index out of range

**Comment by ddss** [comment]
Este erro é devido à incompatibilidade do MT-PEU com a versão do PSO do branch aprimoramento.

incompatibilidade: uso de histórico menor do que o número máximo de iterações.

A issue #77 já trata desta questão.

-> Não é blocker por que não existe nenhum commit que compatibiliza do MT-PEU com o PSO.

Soluções:

```python
- n_historico = número máximo de iterações
- metoddo = {..., 'parada':['itmax']} 
```

**Comment by ddss** [comment]
Atendido no commit 05cf818fd2ef85a85855248db7cc7c3c897b88ec
